create requirements
NikolayMalykhin/ASCEM pull request #1
Opened 2021-05-04 14:36 UTC by NikolayMalykhin

add link on User story map

2021-05-07 08:24 UTC, elukianov requested changes

2021-05-07 08:24 UTC, elukianov commented on 1_requirements.txt
> +https://miro.com/app/board/o9J_lGSEKgk=/
1. Write an application for connection - не совсем понял о чем тут речь. Наши счетчики сами передают нам данные. И даже если нам нужно что-то написать, то это результат истории скорее, нежели её часть.

2. Create user account - лучше пользоваться терминами предметной области. У нас это не пользователь, а абонент. Более того, уже даже используется термин subscriber.

3. Payments of bills on a monthly/Release 1 - я так понимаю, тут опять закрались технические задачки. Карта описывает поведение пользователя/системы, а не разработчика. Далее, когда мы будем детализировать историю, то такие задачи действительно появятся, но это будут именно задачи.

4. Input data validation system и всё что рядом с ним - тут видимо подразумеваются какие-то системы, но это опять же не истории.

2021-05-07 12:25 UTC, NikolayMalykhin commented on 1_requirements.txt
> +https://miro.com/app/board/o9J_lGSEKgk=/
@elukianov fixed.

2021-05-10 07:12 UTC, elukianov commented on 1_requirements.txt
> +https://miro.com/app/board/o9J_lGSEKgk=/
1. Writing connection request - так и не понял что это
2. Check that the data can be retrieved 24/7 - как это выглядит для пользователя? Я тут не вижу истории
3. EM activiti monitoring system - тоже выглядит как фича, а не как история. И как раз от фич мы и пытаемся уйти.

Фреймворк истории выглядит так: "Как <роль> я <что-то делаю>, чтобы <получить результат>"

2021-05-10 07:14 UTC, elukianov requested changes
см коммент к треду

2021-05-11 05:41 UTC, NikolayMalykhin commented
@elukianov I changed second and third and wrote an explanation

Writing connection request: Абонент пишет заявление на подключение -> as a subscriber i want to write connection request
Check that the data can be retrieved 24/7: Для системы получения данных с прибора учёта хотелось бы организовать хранилище, которое бы принимало данные с них 24/7 с минимумом простоев -> as OD i want to be shure that the data can be retrieved 24/7
EM activiti monitoring system: мы хотели иметь возможность отслеживать устройства, которые перестали посылать нам данные -> as OD I want to be able to check the activity of EM

2021-05-11 07:05 UTC, elukianov requested changes

2021-05-11 07:05 UTC, elukianov commented on 1_requirements.txt
> +https://miro.com/app/board/o9J_lGSEKgk=/
2. Поменялась формулировка, но я так ине понял, как это может выглядеть

И ещё для историй, которые не автоматические лучше добавить конкретную роль кто это выполняет. Не просто Pricing Department, а прямо таки Оператор.  Почему так - мы когда будет рисовать интерфейсы по этим историям не будем понимать для кого они и к кому идти, чтобы их протестировать.

2021-06-04 06:18 UTC, merged